global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - 'alert.rules.yaml'
alerting:
  alertmanagers:
    - static_configs:
      - targets:
        - 'alertmanager:9093'
      scheme: http
      timeout: 10s
      api_version: v2
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
        - localhost:9090
  - job_name: xpto-api
    metrics_path: /metrics
    static_configs:
      - targets: 
         - host.docker.internal:3000