apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xpto-api
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: app
  project: default
  source:
    path: charts/app
    repoURL: https://github.com/anaecouto/xpto-api
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true