apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
 name: k8s-action-runner
 namespace: github-actions
spec:
 replicas: 2
 template:
   spec:
     repository: anaecouto/xpto-api