name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted 

    steps:
    - uses: actions/checkout@v3

    - name: Run build image
      run: make build-image

    - name: Run tag image
      run: make tag-image

    - name: Run push image
      run: make push-image
